language: java
dist: xenial
jdk:
  - openjdk8

branches:
  only:
    - master
    - release

notifications:
  email: false

before_install:
  - |
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.txt)|(\.png)|(\.jpg)|(\.gif)|^(LICENSE)|^(docs)'
      status_codes=( ${PIPESTATUS[*]} ); git_diff_status=${status_codes[0]}; grep_status=${status_codes[1]}
      if [[ $git_diff_status == 0 && $grep_status == 1 && $TRAVIS_PULL_REQUEST != "false" ]]
      then
        echo "Only doc files or images were updated in PR, not running the CI."
        exit
      fi
  - nvm install 12

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/executionHistory/
  - rm -rf $HOME/.gradle/caches/*/fileContent/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/
  - rm -rf $HOME/.gradle/caches/*/javaCompile/
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts/
  - rm -rf $HOME/.gradle/caches/*/workerMain/
  - rm -rf $HOME/.gradle/caches/*/gc.properties
  - rm -rf $HOME/.gradle/caches/journal-1/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - angular-build

jobs:
  allow_failures:
    - script: ./e2e-saucelabs.sh
  include:
    - stage: "Prepare Dependencies"
      name: "Prepare Dependencies"
      script:
        - ./gradlew downloadDependencies downloadTestDependencies downloadLinters
    - stage: "Lint/Test"
      name: "Lint"
      script:
        - ./gradlew createConfigs testClasses
        - ./gradlew lint --continue
        - npm ci
        - npm run lint
    - name: "Component Tests"
      script:
        - ./gradlew createConfigs componentTests
        - ./gradlew jacocoReport
        - ./gradlew generateTypes
        - npm ci
        - npm run coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "E2E Tests - Firefox"
      if: branch != master OR type != push OR env(SAUCE_ACCESS_KEY) IS blank OR env(SAUCE_USERNAME) IS blank
      addons:
        firefox: "76.0"
      services:
        - xvfb
      before_script:
        - cd $HOME
        - curl -fsSL -o geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
        - tar -xzf geckodriver.tar.gz
        - cd $TRAVIS_BUILD_DIR
        - mv src/e2e/resources/test.travis.properties src/e2e/resources/test.properties
        - ./gradlew createConfigs testClasses generateTypes
        - npm ci
        - npm run build -- --progress=false
        - ./gradlew appengineStart
      script:
        - ./gradlew e2eTests
    - name: "E2E Tests - Chrome"
      if: branch != master OR type != push OR env(SAUCE_ACCESS_KEY) IS blank OR env(SAUCE_USERNAME) IS blank
      addons:
        chrome: stable
      services:
        - xvfb
      before_script:
        - cd $HOME
        - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
        - curl -fsSL -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        - unzip chromedriver.zip
        - cd $TRAVIS_BUILD_DIR
        - mv src/e2e/resources/test.travis-chrome.properties src/e2e/resources/test.properties
        - ./gradlew createConfigs testClasses generateTypes
        - npm ci
        - npm run build -- --progress=false
        - ./gradlew appengineStart
      script:
        - ./gradlew e2eTests
    - stage: "Prepare for E2E Tests"
      name: "Prepare for E2E Tests"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      script:
        - ./gradlew createConfigs testClasses generateTypes
        - npm ci
        - npm run build -- --progress=false
        - rm -rf angular-build
        - mkdir angular-build
        - cp -r src/main/webapp/. angular-build
    - stage: "E2E Tests - 1"
      name: "Chrome - Windows 10"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="chrome; latest; Windows 10"
      script: ./e2e-saucelabs.sh
    - name: "Firefox - Windows 10"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="firefox; latest; Windows 10"
      script: ./e2e-saucelabs.sh
    - stage: "E2E Tests - 2"
      name: "Chrome - High Sierra"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="chrome; latest; macOS 10.13"
      script: ./e2e-saucelabs.sh
    - name: "Firefox - High Sierra"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="firefox; latest; macOS 10.13"
      script: ./e2e-saucelabs.sh
    - stage: "E2E Tests - 3"
      name: "Edge - Windows 10"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="edge; latest; Windows 10"
      script: ./e2e-saucelabs.sh
    - name: "Safari - High Sierra"
      if: branch = master AND type = push AND env(SAUCE_ACCESS_KEY) IS present AND env(SAUCE_USERNAME) IS present
      addons:
        sauce_connect: true
      before_script: export SAUCELABS_SETTINGS="safari; latest; macOS 10.13"
      script: ./e2e-saucelabs.sh
