language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master
    - release

notifications:
  email: false

sudo: required
dist: trusty

addons:
  firefox: "46.0"

before_install:
  - |
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.txt)|(.png)|(.jpg)|(.gif)|^(LICENSE)|^(docs)'
      status_codes=( ${PIPESTATUS[*]} ); git_diff_status=${status_codes[0]}; grep_status=${status_codes[1]}
      if [[ $git_diff_status == 0 && $grep_status == 1 ]]
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid \
    --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"

before_script:
  - export DISPLAY=:99.0
  - tar -xjf /tmp/firefox-46.0.tar.bz2 --directory $TRAVIS_BUILD_DIR/
  - export PATH="$TRAVIS_BUILD_DIR/firefox:$PATH"
  - export PATH="./node_modules/.bin":$PATH
  - ./gradlew createConfigs testClasses
  - ./gradlew downloadStaticAnalysisTools --continue
  - ./gradlew staticAnalysis --continue

install: true
script:
  - ./gradlew appengineRun ciTests

after_failure:
  - gem install gist
  - ./gradlew generateFailedCmd

after_success:
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true

after_script:
  - ./gradlew appengineStop
env:
  global:
    - secure: j/N7bm0KToA3MYjsCJyS19GQgopqGFCvYjIgpZRFjc9+ye0uUtCfcT3amtoQUSpMcshJICatJnyG3SGZGM2mO/GjdC2rSP0lkfxyj+ZEhL0XHcZxkcQqrJmDcLAn3tbp/lPXGph+bmzyyGbm1Xnx2shUpiQFRCDeY87eWHbQkSb2bTUyiClOlqyfAwoJT9wS+aUFi/XSMUylBH2XxVK1DNqFIuwC288maQXY7U7KA1/JTiDMBQx8xxttTnMUlj1KyhVOPgv1Lsxwz2J4l/DKtfcCERs2znIsEJIing55v4esy9H3/8PObEZI7LNqke9GMdrdYSr3JfvlqZOb4ctOkGxRMUUZETVHb4eAlS04zxbgb4RcrzBdiH5LPSWYfMeaL+0BHn72rfl4JAuT+JiklLmWyoraOU8fier80RUDb17axmm9NAv1KPKCJixArLA6ArpTonKNJKeScmH1NlBIzWjExWPdL8bPnCTiS2j1Qfh1eiPufwOMpP6O4PYZTLnjF4kJVy78PdB1ROYgvnr2VPu6XEsKgzSm9gl0uvIkfo65yXWJCy0K8RJTHjQ0ucl1+Zx3gWdu5/SKNW4YC3KeMfgB13MZZqg7ZUobSzeRbHz25dkbH29dB6s7sKBcjKfhlJN9xAg0I2II0ejcPcWEEp9J1kg2cqB7NO+0a7UdIrk=
    - secure: Lgra3vdcIfo381PLjd6oPFL3zM9MNvX+I351Y8A3CeD2QJCqBvU0C3vsVn43MCn+vmE+PewdsAsc9JN5c66igzbQdd83iS/uP6TTICQxTPWoQjCLIDHO1I5aBMYFh+mG5cGxNWq/oEeLGf/5Dk/k6+mlSRuv9s1rJDRW72iUfMDhoMRAMLwBBGK/rIgBqWzcb4QbVEMPRPArW9fd0WYvfjK2kbi77pikUUx4IR1q9hx+YIdquzDwAmJ6yiUvo7FFawU18FcrNj3OIsWZsO+gYpyQJOQdIZCpD4hJnvUYK3+e5Gv4gknVpqKHxuzNLpDhQMgBTv0krmKCJpo7DsLwfSx07rKcrMMy1JQnWOnE7gUUNnDUWcKIS347+X6T+BQUHWzftJgT2pvnef5kk90Ffq42xxZ8Sbnqtmak85y63LFBSampS6CnD1XczWRgwjIEhrEE6FOGhvUDSheqgWtY/MhTO4c1gbsgFkMJKEgrwyopWNyfWhiRm1gz2cO9EM3nXr8TmPs0IK0riap1GrBl7mHKqp2gixnIPqix7fR0NovOR1043lQAPfCf0Y6gcyMwth9O0Ak+cPqU9mJFL7oC2r/1RuXRjCeRWgMVM/or8fKR7gQ1sP9anX4FXMpotyyjegBvthgiWj0h2vD/EvwEtiSvk4GUyWaoYb44Z5yMn+8=
