environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

init:
  - git config --global core.autocrlf true

branches:
  only:
    - master
    - release

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.gif'
    - LICENSE
    - docs/**/*
    - .templates/**/*

install:
  - npm install

build_script:
  - gradlew.bat createConfigs testClasses

test_script:
  - npm run build
  - gradlew.bat appengineRun ciTests
