environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0

init:
  - git config --global core.autocrlf true

install:
  - choco install firefox -version 46.0

build_script:
  - gradlew.bat createConfigs testClasses 

test_script:
  - gradlew.bat appengineRun travisTests

on_finish:
  - gradlew.bat appengineStop
