environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node 12

branches:
  only:
    - master
    - release
    - csv-migration

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.gif'
    - LICENSE
    - docs/**/*

build_script:
  - gradlew.bat createConfigs testClasses
  - gradlew.bat downloadLinters
  - gradlew.bat lint --continue
  - gradlew.bat componentTests
  - npm install
  - npm run lint
  - gradlew.bat generateTypes
  - npm run coverage
