name: Accessibility Tests

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
jobs:
  axe-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Update Property File
        run: mv src/e2e/resources/test.ci-${{ matrix.browser }}.properties src/e2e/resources/test.properties
      - name: Run Solr search service + local Datastore emulator
        run: docker compose up -d
      - name: Create Config Files
        run: ./gradlew createConfigs testClasses generateTypes
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Build Frontend Bundle
        run: npm run build
      - name: Start Server
        run: |
          ./gradlew serverRun &
          ./wait-for-server.sh
      - name: Start Tests
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew axeTests
          
          echo "ğŸŒ Checking if home page is reachable before tests..."
          curl --fail --retry 5 --retry-delay 5 http://localhost:8080 || exit 1

          echo "ğŸ” Checking if admin page is reachable before tests..."
          curl --fail --retry 5 --retry-delay 5 http://localhost:8080/admin/adminHomePage || exit 1

