name: Build doc site

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master 
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    name: dev docs
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i -g markbind-cli@3.1.1
      - run: |
          cd docs
          markbind build
      - uses: actions/github-script@v6
        id: check-error
        with:
          script: |
            const fs = require('fs');
            // check if build directory exists
            const dir = './docs/_site';

            // check if directory exists
            if (fs.existsSync(dir)) {
                console.log('Built exists!');
            } else {
                console.log('Built not found.');
                core.setFailed('Developer Documentation Error!')
            }
      - name: Deploy on push
        if: ${{ success() && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          markbind deploy --ci
