name: L&P Tests

on:
  push:
    branches:
      - master 
      - release
  schedule:
    - cron: "0 0 * * *" # end of every day
jobs:
  LnP-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('.gradle/*.gradle*', 'build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create Config Files
        run: ./gradlew createConfigs
      - name: Run Solr search service + local Datastore emulator
        run: docker compose up -d
      - name: Start Server
        run: ./gradlew serverRun &
      - name: Wait until server is running
        run: ./wait-for-server.sh
      - name: Start Tests
        run: ./gradlew lnpTests
